import type { StackCategory, StackTool, StackPreset } from "./types";

export const STACK_CATEGORIES: StackCategory[] = [
  { id: "edr",      name: "EDR / AV",             icon: "🛡",  color: "#ef4444", isCoreRequired: true  },
  { id: "siem",     name: "SIEM",                 icon: "📊",  color: "#8b5cf6", isCoreRequired: false },
  { id: "email",    name: "Email Security",        icon: "📧",  color: "#3b82f6", isCoreRequired: false },
  { id: "identity", name: "Identity & PAM",        icon: "🔑",  color: "#f59e0b", isCoreRequired: false },
  { id: "backup",   name: "Backup & DR",           icon: "💾",  color: "#10b981", isCoreRequired: true  },
  { id: "vuln",     name: "Vulnerability Mgmt",    icon: "🔍",  color: "#f97316", isCoreRequired: false },
  { id: "dns",      name: "DNS Filtering",         icon: "🌐",  color: "#06b6d4", isCoreRequired: false },
  { id: "mfa",      name: "MFA / Passwordless",    icon: "🔐",  color: "#ec4899", isCoreRequired: true  },
  { id: "sat",      name: "Security Awareness",    icon: "🎓",  color: "#84cc16", isCoreRequired: false },
  { id: "docs",     name: "Documentation",         icon: "📝",  color: "#64748b", isCoreRequired: false },
  { id: "rmm",      name: "RMM",                  icon: "🖥",   color: "#a78bfa", isCoreRequired: true  },
  { id: "psa",      name: "PSA / Ticketing",       icon: "🎫",  color: "#34d399", isCoreRequired: true  },
  { id: "netmon",   name: "Network Monitoring",    icon: "📡",  color: "#38bdf8", isCoreRequired: false },
  { id: "other",    name: "Other",                 icon: "🔧",  color: "#94a3b8", isCoreRequired: false },
];

export const STACK_TOOLS: StackTool[] = [
  // ── Endpoint Protection ────────────────────────────────────────────
  {
    id: "crowdstrike-falcon-go",
    name: "Falcon Go",
    vendor: "CrowdStrike",
    categoryId: "edr",
    displayCategory: "Endpoint Protection",
    shortDescription: "AI-powered threat detection for SMB endpoints.",
    costMonthly: 5.99,
    msrpMonthly: 10.00,
    notes: "Entry-level EDR with AI-powered threat detection. Ideal for SMB endpoints.",
    tags: ["cloud-native"],
  },
  {
    id: "huntress-edr",
    name: "Managed EDR",
    vendor: "Huntress",
    categoryId: "edr",
    displayCategory: "Endpoint Protection",
    shortDescription: "24/7 SOC-backed managed EDR built for MSPs.",
    costMonthly: 3.50,
    msrpMonthly: 7.00,
    notes: "MSP-first managed EDR. 24/7 SOC + ransomware canaries included.",
    tags: ["high-margin", "msp-first"],
  },
  {
    id: "sentinelone-control",
    name: "SentinelOne Control",
    vendor: "SentinelOne",
    categoryId: "edr",
    displayCategory: "Endpoint Protection",
    shortDescription: "Autonomous EDR with one-click rollback.",
    costMonthly: 6.00,
    msrpMonthly: 10.50,
    notes: "Autonomous EDR with Storyline. Strong rollback capability.",
  },
  {
    id: "defender-p2",
    name: "Defender for Endpoint P2",
    vendor: "Microsoft",
    categoryId: "edr",
    displayCategory: "Endpoint Protection",
    shortDescription: "Built-in EDR for Microsoft 365 environments.",
    costMonthly: 5.00,
    msrpMonthly: 8.00,
    notes: "Built into Microsoft 365. Lower overhead for M365-heavy clients.",
  },

  // ── Threat Detection & SIEM ───────────────────────────────────────
  {
    id: "blumira-siem",
    name: "Blumira SIEM + XDR",
    vendor: "Blumira",
    categoryId: "siem",
    displayCategory: "Threat Detection & SIEM",
    shortDescription: "Cloud SIEM with zero log-shipping complexity.",
    costMonthly: 7.00,
    msrpMonthly: 13.00,
    notes: "Cloud SIEM built for MSPs. No log-shipping complexity.",
    tags: ["high-margin", "msp-first"],
  },
  {
    id: "sentinel-siem",
    name: "Microsoft Sentinel",
    vendor: "Microsoft",
    categoryId: "siem",
    displayCategory: "Threat Detection & SIEM",
    shortDescription: "Pay-per-GB ingestion SIEM native to Azure.",
    costMonthly: 2.46,
    msrpMonthly: 5.00,
    notes: "Pay-per-GB ingestion model. Best for M365-native orgs.",
  },
  {
    id: "logrhythm-axon",
    name: "LogRhythm Axon",
    vendor: "LogRhythm",
    categoryId: "siem",
    displayCategory: "Threat Detection & SIEM",
    shortDescription: "Enterprise SIEM with UEBA and advanced analytics.",
    costMonthly: 8.50,
    msrpMonthly: 15.00,
    notes: "Enterprise-grade SIEM with UEBA. Higher setup complexity.",
  },

  // ── Email Security ────────────────────────────────────────────────
  {
    id: "proofpoint-essentials",
    name: "Proofpoint Essentials",
    vendor: "Proofpoint",
    categoryId: "email",
    displayCategory: "Email Security",
    shortDescription: "URL rewriting, sandboxing, and spam filtering.",
    costMonthly: 3.00,
    msrpMonthly: 5.50,
    notes: "URL rewriting, sandboxing, spam filtering for SMB.",
  },
  {
    id: "mimecast-email",
    name: "Mimecast Email Security",
    vendor: "Mimecast",
    categoryId: "email",
    displayCategory: "Email Security",
    shortDescription: "Email threat protection + cloud-to-cloud backup.",
    costMonthly: 3.75,
    msrpMonthly: 7.00,
    notes: "Cloud-to-cloud backup + advanced email threat protection.",
    tags: ["high-margin"],
  },
  {
    id: "defender-email",
    name: "Defender for Office 365 P1",
    vendor: "Microsoft",
    categoryId: "email",
    displayCategory: "Email Security",
    shortDescription: "Safe Links + Safe Attachments for M365.",
    costMonthly: 2.00,
    msrpMonthly: 4.00,
    notes: "Safe links + safe attachments. Already included in M365 BP.",
  },

  // ── Identity & Access Management ──────────────────────────────────
  {
    id: "cyberark-privilege",
    name: "CyberArk Privilege Cloud",
    vendor: "CyberArk",
    categoryId: "identity",
    displayCategory: "Identity & Access Management",
    shortDescription: "Full PAM with session recording and JIT access.",
    costMonthly: 7.50,
    msrpMonthly: 14.00,
    notes: "Full PAM. Session recording, credential vaulting, JIT access.",
  },
  {
    id: "delinea-server",
    name: "Delinea Secret Server",
    vendor: "Delinea",
    categoryId: "identity",
    displayCategory: "Identity & Access Management",
    shortDescription: "On-prem or cloud PAM for regulated industries.",
    costMonthly: 5.00,
    msrpMonthly: 9.50,
    notes: "On-prem or cloud PAM. Good for regulated industries.",
  },

  // ── Backup & Recovery ─────────────────────────────────────────────
  {
    id: "veeam-m365",
    name: "Veeam Backup for M365",
    vendor: "Veeam",
    categoryId: "backup",
    displayCategory: "Backup & Recovery",
    shortDescription: "Backs up Exchange, SharePoint, OneDrive & Teams.",
    costMonthly: 2.50,
    msrpMonthly: 5.00,
    notes: "Exchange, SharePoint, OneDrive, Teams backup. Per-user licensing.",
    tags: ["high-margin"],
  },
  {
    id: "acronis-cyber",
    name: "Acronis Cyber Protect Cloud",
    vendor: "Acronis",
    categoryId: "backup",
    displayCategory: "Backup & Recovery",
    shortDescription: "Backup + endpoint security in a single agent.",
    costMonthly: 3.20,
    msrpMonthly: 6.50,
    notes: "Backup + endpoint security bundled. Storage-based pricing.",
  },
  {
    id: "datto-saas",
    name: "Datto SaaS Protection",
    vendor: "Datto",
    categoryId: "backup",
    displayCategory: "Backup & Recovery",
    shortDescription: "M365 & Google Workspace backup with point-in-time restore.",
    costMonthly: 2.80,
    msrpMonthly: 5.50,
    notes: "M365 + Google Workspace backup. Point-in-time restore.",
  },

  // ── Vulnerability Management ──────────────────────────────────────
  {
    id: "tenable-io",
    name: "Tenable.io",
    vendor: "Tenable",
    categoryId: "vuln",
    displayCategory: "Vulnerability Management",
    shortDescription: "Continuous asset scanning with risk prioritization.",
    costMonthly: 3.50,
    msrpMonthly: 7.00,
    notes: "Asset inventory + continuous vulnerability scanning.",
    tags: ["high-margin"],
  },
  {
    id: "rapid7-insight",
    name: "InsightVM",
    vendor: "Rapid7",
    categoryId: "vuln",
    displayCategory: "Vulnerability Management",
    shortDescription: "Live dashboards with guided remediation workflows.",
    costMonthly: 4.00,
    msrpMonthly: 7.50,
    notes: "Live dashboards with remediation workflows.",
  },

  // ── DNS & Web Filtering ───────────────────────────────────────────
  {
    id: "dnsfilter",
    name: "DNSFilter",
    vendor: "DNSFilter",
    categoryId: "dns",
    displayCategory: "DNS & Web Filtering",
    shortDescription: "AI-driven DNS filtering with per-client reporting.",
    costMonthly: 1.10,
    msrpMonthly: 2.50,
    notes: "AI-driven domain categorization. MSP console with client reporting.",
    tags: ["high-margin", "msp-first"],
  },
  {
    id: "cisco-umbrella",
    name: "Umbrella DNS Essentials",
    vendor: "Cisco",
    categoryId: "dns",
    displayCategory: "DNS & Web Filtering",
    shortDescription: "DNS + proxy layer with enterprise brand credibility.",
    costMonthly: 2.20,
    msrpMonthly: 4.00,
    notes: "DNS + proxy layer. Strong brand recognition with enterprise clients.",
  },

  // ── Multi-Factor Authentication ───────────────────────────────────
  {
    id: "duo-essentials",
    name: "Duo Essentials",
    vendor: "Cisco",
    categoryId: "mfa",
    displayCategory: "Multi-Factor Authentication",
    shortDescription: "MFA for all apps with device trust and passwordless push.",
    costMonthly: 3.00,
    msrpMonthly: 5.50,
    notes: "MFA for all apps. Device trust + passwordless push.",
  },
  {
    id: "entra-mfa",
    name: "Microsoft Entra MFA",
    vendor: "Microsoft",
    categoryId: "mfa",
    displayCategory: "Multi-Factor Authentication",
    shortDescription: "Native Azure AD MFA included in Entra ID P1.",
    costMonthly: 2.00,
    msrpMonthly: 4.00,
    notes: "Included in Entra ID P1. Native Azure AD integration.",
  },

  // ── Security Awareness Training ───────────────────────────────────
  {
    id: "knowbe4",
    name: "KnowBe4 Essentials",
    vendor: "KnowBe4",
    categoryId: "sat",
    displayCategory: "Security Awareness Training",
    shortDescription: "Phishing simulations and a huge training library.",
    costMonthly: 1.50,
    msrpMonthly: 3.00,
    notes: "Phishing simulations + training library. Per-user per-month.",
    tags: ["high-margin"],
  },

  // ── Remote Monitoring & Management ───────────────────────────────
  {
    id: "ninjarmm",
    name: "NinjaRMM",
    vendor: "NinjaOne",
    categoryId: "rmm",
    displayCategory: "Remote Monitoring & Management",
    shortDescription: "Modern RMM with patch management and remote access.",
    costMonthly: 3.00,
    msrpMonthly: 5.50,
    notes: "Patch management, remote access, scripting. Fast + modern UI.",
    tags: ["msp-first"],
  },
  {
    id: "connectwise-automate",
    name: "Automate",
    vendor: "ConnectWise",
    categoryId: "rmm",
    displayCategory: "Remote Monitoring & Management",
    shortDescription: "Deep automation engine for complex MSP environments.",
    costMonthly: 2.50,
    msrpMonthly: 4.50,
    notes: "Deep automation engine. Steeper learning curve.",
  },

  // ── PSA & Ticketing ───────────────────────────────────────────────
  {
    id: "halo-psa",
    name: "HaloPSA",
    vendor: "HaloITSM",
    categoryId: "psa",
    displayCategory: "PSA & Ticketing",
    shortDescription: "Full PSA: tickets, SLAs, billing, and contracts.",
    costMonthly: 35.00,
    msrpMonthly: 60.00,
    notes: "Full PSA: tickets, SLAs, billing, contracts. Flat per-technician.",
  },
  {
    id: "connectwise-manage",
    name: "Manage",
    vendor: "ConnectWise",
    categoryId: "psa",
    displayCategory: "PSA & Ticketing",
    shortDescription: "Mature PSA with deep RMM and accounting integrations.",
    costMonthly: 40.00,
    msrpMonthly: 70.00,
    notes: "Mature PSA. Deep integrations with RMM and accounting.",
  },

  // ── Network Monitoring ────────────────────────────────────────────
  {
    id: "prtg",
    name: "PRTG Network Monitor",
    vendor: "Paessler",
    categoryId: "netmon",
    displayCategory: "Network Monitoring",
    shortDescription: "Sensor-based SNMP + flow monitoring for all devices.",
    costMonthly: 1.80,
    msrpMonthly: 3.50,
    notes: "Sensor-based pricing. SNMP + flow + REST monitoring.",
  },
];

export const STACK_PRESETS: StackPreset[] = [
  {
    id: "essential-5",
    label: "Essential 5",
    description: "The non-negotiables: EDR, MFA, Backup, Email & DNS",
    emoji: "⚡",
    toolIds: [
      "huntress-edr",
      "duo-essentials",
      "veeam-m365",
      "proofpoint-essentials",
      "dnsfilter",
    ],
  },
  {
    id: "full-coverage",
    label: "Full Coverage",
    description: "Best-in-class across all 13 security categories",
    emoji: "🛡",
    toolIds: [
      "huntress-edr",
      "blumira-siem",
      "mimecast-email",
      "delinea-server",
      "veeam-m365",
      "tenable-io",
      "dnsfilter",
      "duo-essentials",
      "knowbe4",
      "ninjarmm",
      "halo-psa",
      "prtg",
    ],
  },
  {
    id: "lean-profit",
    label: "Lean & Profitable",
    description: "High-margin tools only — maximize your take-home",
    emoji: "💰",
    toolIds: [
      "huntress-edr",
      "blumira-siem",
      "mimecast-email",
      "veeam-m365",
      "tenable-io",
      "dnsfilter",
      "knowbe4",
    ],
  },
];
