import type { ToolCategory, PricingModel, TierMetric, TierRule } from "@/lib/types";

export interface VendorEntry {
  id: string;
  name: string;
  vendor: string;
  category: ToolCategory;
  description: string;
  pricing_model: PricingModel;
  per_seat_cost: number;
  flat_monthly_cost: number;
  annual_flat_cost: number;
  per_user_cost: number;
  per_org_cost: number;
  tier_rules: TierRule[];
  tier_metric?: TierMetric;
  vendor_minimum_monthly: number | null;
  support_complexity: number;
  renewal_uplift_pct: number;
}

export const VENDOR_CATALOG: VendorEntry[] = [
  // ── EDR ──────────────────────────────────────────────────────────────────
  {
    id: "eset-mdr",
    name: "ESET MDR",
    vendor: "ESET",
    category: "edr",
    description: "Managed detection & response with 24/7 SOC coverage",
    pricing_model: "per_seat",
    per_seat_cost: 3.0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 2,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "huntress-mdr",
    name: "Huntress Managed EDR",
    vendor: "Huntress",
    category: "edr",
    description: "Persistent foothold detection + managed remediation for SMBs",
    pricing_model: "per_seat",
    per_seat_cost: 3.5,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 2,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "sentinelone-control",
    name: "SentinelOne Control",
    vendor: "SentinelOne",
    category: "edr",
    description: "AI-powered autonomous endpoint protection and response",
    pricing_model: "per_seat",
    per_seat_cost: 4.0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 3,
    renewal_uplift_pct: 0.05,
  },
  {
    id: "crowdstrike-falcon-go",
    name: "CrowdStrike Falcon Go",
    vendor: "CrowdStrike",
    category: "edr",
    description: "Next-gen AV with behavioral AI and threat intelligence",
    pricing_model: "per_seat",
    per_seat_cost: 5.0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 3,
    renewal_uplift_pct: 0.05,
  },
  {
    id: "ms-defender-endpoint",
    name: "Microsoft Defender for Endpoint",
    vendor: "Microsoft",
    category: "edr",
    description: "Microsoft-native EDR included with M365 Business Premium",
    pricing_model: "per_user",
    per_seat_cost: 0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 2.0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 3,
    renewal_uplift_pct: 0.03,
  },

  // ── SIEM ─────────────────────────────────────────────────────────────────
  {
    id: "blumira-siem",
    name: "Blumira SIEM",
    vendor: "Blumira",
    category: "siem",
    description: "Automated SIEM + detection with playbook-driven response",
    pricing_model: "flat_monthly",
    per_seat_cost: 0,
    flat_monthly_cost: 200,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: 200,
    support_complexity: 3,
    renewal_uplift_pct: 0.05,
  },
  {
    id: "datto-siem",
    name: "Datto SIEM",
    vendor: "Datto",
    category: "siem",
    description: "MSP-native SIEM with multi-tenant management portal",
    pricing_model: "flat_monthly",
    per_seat_cost: 0,
    flat_monthly_cost: 150,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: 150,
    support_complexity: 3,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "ms-sentinel",
    name: "Microsoft Sentinel",
    vendor: "Microsoft",
    category: "siem",
    description: "Cloud-native SIEM with ML analytics on Azure",
    pricing_model: "per_seat",
    per_seat_cost: 2.0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 4,
    renewal_uplift_pct: 0.03,
  },

  // ── Email Security ────────────────────────────────────────────────────────
  {
    id: "proofpoint-essentials",
    name: "Proofpoint Essentials",
    vendor: "Proofpoint",
    category: "email_security",
    description: "Email filtering, anti-phishing, and archiving for SMBs",
    pricing_model: "per_user",
    per_seat_cost: 0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 2.5,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 2,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "mimecast",
    name: "Mimecast Email Security",
    vendor: "Mimecast",
    category: "email_security",
    description: "Advanced threat protection, continuity, and archiving",
    pricing_model: "per_user",
    per_seat_cost: 0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 3.0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 2,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "ms-defender-email",
    name: "Microsoft Defender for Email",
    vendor: "Microsoft",
    category: "email_security",
    description: "Built-in Exchange Online Protection + Defender add-on",
    pricing_model: "per_user",
    per_seat_cost: 0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 2.0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 2,
    renewal_uplift_pct: 0.03,
  },

  // ── MFA / Identity ────────────────────────────────────────────────────────
  {
    id: "duo-mfa",
    name: "Duo MFA",
    vendor: "Cisco",
    category: "mfa",
    description: "Trusted access MFA — phone push, biometric, hardware keys",
    pricing_model: "per_user",
    per_seat_cost: 0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 3.0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 2,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "ms-entra-id",
    name: "Microsoft Entra ID P1",
    vendor: "Microsoft",
    category: "identity",
    description: "Conditional access, SSPR, and identity governance",
    pricing_model: "per_user",
    per_seat_cost: 0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 6.0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 3,
    renewal_uplift_pct: 0.03,
  },

  // ── Backup ────────────────────────────────────────────────────────────────
  {
    id: "veeam-m365",
    name: "Veeam M365 Backup",
    vendor: "Veeam",
    category: "backup",
    description: "Immutable backup for Exchange, SharePoint, OneDrive & Teams",
    pricing_model: "per_user",
    per_seat_cost: 0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 2.0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 2,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "datto-bcdr",
    name: "Datto BCDR",
    vendor: "Datto",
    category: "backup",
    description: "Business continuity with local + cloud backup and instant virtualisation",
    pricing_model: "flat_monthly",
    per_seat_cost: 0,
    flat_monthly_cost: 150,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: 150,
    support_complexity: 2,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "acronis-protect",
    name: "Acronis Cyber Protect",
    vendor: "Acronis",
    category: "backup",
    description: "Integrated backup + endpoint protection in one agent",
    pricing_model: "per_seat",
    per_seat_cost: 3.5,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 2,
    renewal_uplift_pct: 0.03,
  },

  // ── Vulnerability Management ───────────────────────────────────────────────
  {
    id: "tenable-io",
    name: "Tenable.io",
    vendor: "Tenable",
    category: "vulnerability_management",
    description: "Continuous network scanning and risk-based vulnerability management",
    pricing_model: "per_seat",
    per_seat_cost: 2.5,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 3,
    renewal_uplift_pct: 0.05,
  },
  {
    id: "rapid7-insightvm",
    name: "Rapid7 InsightVM",
    vendor: "Rapid7",
    category: "vulnerability_management",
    description: "Live vulnerability risk dashboards + remediation tracking",
    pricing_model: "per_seat",
    per_seat_cost: 3.5,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 3,
    renewal_uplift_pct: 0.05,
  },

  // ── DNS Filtering ─────────────────────────────────────────────────────────
  {
    id: "dnsfilter",
    name: "DNSFilter",
    vendor: "DNSFilter",
    category: "dns_filtering",
    description: "AI-driven DNS-layer security with MSP multi-tenant console",
    pricing_model: "per_seat",
    per_seat_cost: 1.0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 1,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "cisco-umbrella",
    name: "Cisco Umbrella DNS",
    vendor: "Cisco",
    category: "dns_filtering",
    description: "DNS & web layer security with Cisco Talos threat intelligence",
    pricing_model: "per_user",
    per_seat_cost: 0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 2.2,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 2,
    renewal_uplift_pct: 0.03,
  },

  // ── Security Awareness Training ────────────────────────────────────────────
  {
    id: "knowbe4-sat",
    name: "KnowBe4 SAT",
    vendor: "KnowBe4",
    category: "security_awareness_training",
    description: "Phishing simulation + training content library for end users",
    pricing_model: "per_user",
    per_seat_cost: 0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 2.0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 1,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "proofpoint-sat",
    name: "Proofpoint Security Awareness",
    vendor: "Proofpoint",
    category: "security_awareness_training",
    description: "Targeted attack simulation tied to real threat intelligence",
    pricing_model: "per_user",
    per_seat_cost: 0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 1.8,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 1,
    renewal_uplift_pct: 0.03,
  },

  // ── Documentation ─────────────────────────────────────────────────────────
  {
    id: "it-glue",
    name: "IT Glue",
    vendor: "Kaseya",
    category: "documentation",
    description: "Structured IT documentation with password management and runbooks",
    pricing_model: "flat_monthly",
    per_seat_cost: 0,
    flat_monthly_cost: 99,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: 99,
    support_complexity: 1,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "hudu",
    name: "Hudu",
    vendor: "Hudu",
    category: "documentation",
    description: "Modern documentation + password manager built for MSPs",
    pricing_model: "flat_monthly",
    per_seat_cost: 0,
    flat_monthly_cost: 50,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: 50,
    support_complexity: 1,
    renewal_uplift_pct: 0.03,
  },

  // ── RMM ──────────────────────────────────────────────────────────────────
  {
    id: "ninja-rmm",
    name: "NinjaRMM",
    vendor: "NinjaOne",
    category: "rmm",
    description: "Cloud-based RMM with patching, scripting, and remote access",
    pricing_model: "per_seat",
    per_seat_cost: 3.0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 2,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "cw-automate",
    name: "ConnectWise Automate",
    vendor: "ConnectWise",
    category: "rmm",
    description: "Comprehensive RMM with deep automation and scripting engine",
    pricing_model: "per_seat",
    per_seat_cost: 2.5,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 3,
    renewal_uplift_pct: 0.03,
  },

  // ── PSA ──────────────────────────────────────────────────────────────────
  {
    id: "cw-manage",
    name: "ConnectWise Manage",
    vendor: "ConnectWise",
    category: "psa",
    description: "PSA with ticketing, billing, time tracking, and reporting",
    pricing_model: "per_seat",
    per_seat_cost: 2.5,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 3,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "autotask-psa",
    name: "Autotask PSA",
    vendor: "Datto",
    category: "psa",
    description: "MSP PSA with service desk, project management, and billing",
    pricing_model: "flat_monthly",
    per_seat_cost: 0,
    flat_monthly_cost: 99,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: 99,
    support_complexity: 3,
    renewal_uplift_pct: 0.03,
  },

  // ── Network Monitoring ────────────────────────────────────────────────────
  {
    id: "auvik",
    name: "Auvik Network Management",
    vendor: "Auvik",
    category: "network_monitoring",
    description: "Automated network topology mapping + traffic analysis",
    pricing_model: "per_seat",
    per_seat_cost: 3.0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: null,
    support_complexity: 2,
    renewal_uplift_pct: 0.03,
  },
  {
    id: "prtg",
    name: "PRTG Network Monitor",
    vendor: "Paessler",
    category: "network_monitoring",
    description: "On-prem network monitoring with 250+ sensor types",
    pricing_model: "flat_monthly",
    per_seat_cost: 0,
    flat_monthly_cost: 100,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_rules: [],
    vendor_minimum_monthly: 100,
    support_complexity: 3,
    renewal_uplift_pct: 0.03,
  },

  // ── Other (TEM / Threat Intel) ────────────────────────────────────────────
  {
    id: "flare-tem",
    name: "Flare TEM",
    vendor: "Flare",
    category: "other",
    description: "Threat exposure management — dark web + external attack surface",
    pricing_model: "tiered_by_metric",
    per_seat_cost: 0,
    flat_monthly_cost: 0,
    annual_flat_cost: 0,
    per_user_cost: 0,
    per_org_cost: 0,
    tier_metric: "headcount",
    tier_rules: [
      { minSeats: 0, maxSeats: 250, costPerSeat: 0, priceType: "annualFlat", annualFlat: 840 },
      { minSeats: 251, maxSeats: 1000, costPerSeat: 0, priceType: "annualFlat", annualFlat: 2400 },
      { minSeats: 1001, maxSeats: 5000, costPerSeat: 0, priceType: "annualFlat", annualFlat: 6000 },
      { minSeats: 5001, maxSeats: null, costPerSeat: 0, priceType: "annualFlat", annualFlat: 12000 },
    ],
    vendor_minimum_monthly: null,
    support_complexity: 2,
    renewal_uplift_pct: 0.05,
  },
];

/** Vendors grouped by category, in display order */
export const CATALOG_BY_CATEGORY: [
  category: string,
  vendors: VendorEntry[],
][] = [
  ["edr", VENDOR_CATALOG.filter((v) => v.category === "edr")],
  ["mfa", VENDOR_CATALOG.filter((v) => v.category === "mfa")],
  ["email_security", VENDOR_CATALOG.filter((v) => v.category === "email_security")],
  ["backup", VENDOR_CATALOG.filter((v) => v.category === "backup")],
  ["dns_filtering", VENDOR_CATALOG.filter((v) => v.category === "dns_filtering")],
  ["siem", VENDOR_CATALOG.filter((v) => v.category === "siem")],
  ["security_awareness_training", VENDOR_CATALOG.filter((v) => v.category === "security_awareness_training")],
  ["vulnerability_management", VENDOR_CATALOG.filter((v) => v.category === "vulnerability_management")],
  ["rmm", VENDOR_CATALOG.filter((v) => v.category === "rmm")],
  ["psa", VENDOR_CATALOG.filter((v) => v.category === "psa")],
  ["identity", VENDOR_CATALOG.filter((v) => v.category === "identity")],
  ["documentation", VENDOR_CATALOG.filter((v) => v.category === "documentation")],
  ["network_monitoring", VENDOR_CATALOG.filter((v) => v.category === "network_monitoring")],
  ["other", VENDOR_CATALOG.filter((v) => v.category === "other")],
];

export const ENDPOINT_RANGE_LABELS: Record<string, string> = {
  small: "< 25 endpoints",
  smb: "25–100 endpoints",
  mid: "100–500 endpoints",
  enterprise: "500+ endpoints",
};

export const ENDPOINT_RANGE_VALUES: Record<string, number> = {
  small: 15,
  smb: 50,
  mid: 200,
  enterprise: 750,
};
