import type { ProposalContent } from "@/lib/types";

export interface ProposalExportData {
  orgName: string;
  recipientName: string;
  content: ProposalContent;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function formatDate(): string {
  return new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

const SECTION_HEADINGS: { key: keyof ProposalContent; heading: string }[] = [
  { key: "executive_summary", heading: "Executive Summary" },
  { key: "services_overview", heading: "Services Overview" },
  { key: "pricing_summary", heading: "Pricing Summary" },
  { key: "why_us", heading: "Why {orgName}" },
  { key: "risk_snapshot", heading: "Risk Snapshot" },
];

function isBulletLine(line: string): boolean {
  const t = line.trim();
  return t.startsWith("- ") || t.startsWith("• ") || /^\d+\.\s/.test(t);
}

function stripBulletPrefix(line: string): string {
  return line.trim().replace(/^[-•]\s*/, "").replace(/^\d+\.\s*/, "");
}

function sectionToString(value: unknown): string {
  if (typeof value === "string") return value;
  if (Array.isArray(value)) {
    return value
      .map((item) => {
        if (typeof item === "string") return item;
        if (item && typeof item === "object" && "name" in item) {
          return `${item.name}\n${item.description || ""}`;
        }
        return String(item);
      })
      .join("\n\n");
  }
  return String(value ?? "");
}

// ── Brand constants ─────────────────────────────────────────────────────────

const BRAND = {
  dark: "#0A0A0A",
  lime: "#A3FF12",
  white: "#FFFFFF",
  muted: "#999999",
  body: "#333333",
  headerHeight: 60,
} as const;

// ── PDF Generation ──────────────────────────────────────────────────────────

export async function generateProposalPdf(
  data: ProposalExportData
): Promise<Buffer> {
  const PDFDocument = (await import("pdfkit")).default;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "letter",
      margins: { top: 72, bottom: 72, left: 72, right: 72 },
      bufferPages: true,
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageW = doc.page.width;
    const contentWidth = pageW - 144;
    // ── Cover Page ──────────────────────────────────────────────────────

    // Dark header band with logo text
    doc.rect(0, 0, pageW, BRAND.headerHeight).fill(BRAND.dark);
    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .fillColor(BRAND.white)
      .text("STACK", 72, 22, { continued: true })
      .fillColor(BRAND.lime)
      .text("TERYX");

    doc.moveDown(10);
    doc
      .fontSize(28)
      .font("Helvetica-Bold")
      .fillColor(BRAND.body)
      .text(data.orgName, { align: "center", width: contentWidth });

    doc.moveDown(0.5);
    doc
      .fontSize(22)
      .font("Helvetica")
      .fillColor(BRAND.body)
      .text(`Proposal for ${data.recipientName}`, {
        align: "center",
        width: contentWidth,
      });

    doc.moveDown(3);
    doc
      .fontSize(10)
      .fillColor(BRAND.muted)
      .text("Generated by Stackteryx", { align: "center", width: contentWidth });

    doc.moveDown(0.3);
    doc.text(formatDate(), { align: "center", width: contentWidth });

    // ── Content Sections ────────────────────────────────────────────────
    for (const section of SECTION_HEADINGS) {
      const raw = data.content[section.key];
      const body = sectionToString(raw);
      if (!body) continue;

      const heading = section.heading.replace("{orgName}", data.orgName);

      doc.addPage();

      // Section heading — bold uppercase
      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .fillColor(BRAND.body)
        .text(heading.toUpperCase(), { width: contentWidth });

      doc.moveDown(0.3);

      // Lime accent underline (40px wide, 2px)
      const uy = doc.y;
      doc
        .moveTo(72, uy)
        .lineTo(112, uy)
        .strokeColor(BRAND.lime)
        .lineWidth(2)
        .stroke();

      doc.moveDown(0.8);

      // Body text — 10pt with 1.6 line height
      const lines = body.split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (isBulletLine(trimmed)) {
          doc
            .fontSize(10)
            .font("Helvetica")
            .fillColor(BRAND.body)
            .text(`  \u2022  ${stripBulletPrefix(trimmed)}`, {
              lineGap: 6,
              width: contentWidth,
            });
        } else if (trimmed.length > 0) {
          doc
            .fontSize(10)
            .font("Helvetica")
            .fillColor(BRAND.body)
            .text(trimmed, { lineGap: 6, width: contentWidth });
        } else {
          doc.moveDown(0.5);
        }
      }
    }

    // ── Footer on every page ────────────────────────────────────────────
    const range = doc.bufferedPageRange();
    const totalPages = range.count;
    for (let i = 0; i < totalPages; i++) {
      doc.switchToPage(i);
      const footerY = doc.page.height - 50;
      // Left: confidential
      doc
        .fontSize(7)
        .font("Helvetica")
        .fillColor(BRAND.muted)
        .text(
          `Confidential \u2014 Prepared for ${data.recipientName}`,
          72,
          footerY,
          { width: contentWidth / 3, align: "left" }
        );
      // Center: Stackteryx
      doc
        .fontSize(7)
        .text(
          "Stackteryx",
          72 + contentWidth / 3,
          footerY,
          { width: contentWidth / 3, align: "center" }
        );
      // Right: page number
      doc
        .fontSize(7)
        .text(
          `${i + 1} / ${totalPages}`,
          72 + (contentWidth / 3) * 2,
          footerY,
          { width: contentWidth / 3, align: "right" }
        );
    }

    doc.end();
  });
}

// ── DOCX Generation ─────────────────────────────────────────────────────────

export async function generateProposalDocx(
  data: ProposalExportData
): Promise<Buffer> {
  const {
    Document,
    Packer,
    Paragraph,
    TextRun,
    AlignmentType,
    Footer,
    PageBreak,
    BorderStyle,
  } = await import("docx");

  const footerText = `Confidential \u2014 Prepared for ${data.recipientName}`;

  const coverParagraphs = [
    new Paragraph({ spacing: { before: 4000 } }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: data.orgName,
          bold: true,
          size: 56,
          font: "Calibri",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 200 },
      children: [
        new TextRun({
          text: `Proposal for ${data.recipientName}`,
          size: 44,
          font: "Calibri",
          color: "333333",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 1200 },
      children: [
        new TextRun({
          text: "Generated by Stackteryx",
          size: 20,
          font: "Calibri",
          color: "999999",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 100 },
      children: [
        new TextRun({
          text: formatDate(),
          size: 20,
          font: "Calibri",
          color: "999999",
        }),
      ],
    }),
  ];

  const sectionParagraphs: InstanceType<typeof Paragraph>[] = [];

  for (const section of SECTION_HEADINGS) {
    const raw = data.content[section.key];
    const body = sectionToString(raw);
    if (!body) continue;

    const heading = section.heading.replace("{orgName}", data.orgName);

    sectionParagraphs.push(
      new Paragraph({ children: [new PageBreak()] })
    );

    sectionParagraphs.push(
      new Paragraph({
        spacing: { after: 120 },
        border: {
          bottom: {
            style: BorderStyle.SINGLE,
            size: 1,
            color: "E5E5E5",
            space: 8,
          },
        },
        children: [
          new TextRun({
            text: heading,
            bold: true,
            size: 36,
            font: "Calibri",
            color: "1A1A1A",
          }),
        ],
      })
    );

    sectionParagraphs.push(new Paragraph({ spacing: { before: 200 } }));

    const lines = body.split("\n");
    for (const line of lines) {
      const trimmed = line.trim();
      if (isBulletLine(trimmed)) {
        sectionParagraphs.push(
          new Paragraph({
            bullet: { level: 0 },
            spacing: { before: 60, after: 60 },
            children: [
              new TextRun({
                text: stripBulletPrefix(trimmed),
                size: 22,
                font: "Calibri",
                color: "333333",
              }),
            ],
          })
        );
      } else if (trimmed.length > 0) {
        sectionParagraphs.push(
          new Paragraph({
            spacing: { before: 60, after: 60 },
            children: [
              new TextRun({
                text: trimmed,
                size: 22,
                font: "Calibri",
                color: "333333",
              }),
            ],
          })
        );
      } else {
        sectionParagraphs.push(
          new Paragraph({ spacing: { before: 120 } })
        );
      }
    }
  }

  const doc = new Document({
    sections: [
      {
        properties: {},
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: footerText,
                    size: 16,
                    font: "Calibri",
                    color: "999999",
                  }),
                ],
              }),
            ],
          }),
        },
        children: [...coverParagraphs, ...sectionParagraphs],
      },
    ],
  });

  return (await Packer.toBuffer(doc)) as Buffer;
}
