-- Migration 027: Add playbook columns to bundle_enablement
-- Stores the full sales playbook JSON generated by the Sales Enablement mode.

ALTER TABLE bundle_enablement ADD COLUMN IF NOT EXISTS playbook_content      jsonb;
ALTER TABLE bundle_enablement ADD COLUMN IF NOT EXISTS playbook_generated_at timestamptz;
