insert into public.global_tool_library (name, vendor, category, subcategory, description, typical_use_case, pricing_model, typical_cost_low, typical_cost_high, cost_unit, mssp_tier, compliance_tags, tags) values

-- ── ENDPOINT DETECTION & RESPONSE (EDR) ─────────────────────────────────────
('CrowdStrike Falcon', 'CrowdStrike', 'edr', 'Enterprise EDR', 'AI-native endpoint protection with real-time threat intelligence and automated response.', 'Enterprise and mid-market MSPs needing top-tier endpoint protection', 'per_seat', 18, 25, 'seat', 'all', ARRAY['HIPAA','PCI DSS','CMMC','NIST'], ARRAY['endpoint','edr','ai']),
('SentinelOne Singularity', 'SentinelOne', 'edr', 'AI EDR', 'Autonomous AI-powered endpoint protection, detection, and response.', 'MSPs wanting fully autonomous threat response with minimal analyst time', 'per_seat', 15, 22, 'seat', 'all', ARRAY['HIPAA','PCI DSS','CMMC'], ARRAY['endpoint','edr','autonomous']),
('Microsoft Defender for Endpoint', 'Microsoft', 'edr', 'Integrated EDR', 'Built-in EDR for Microsoft 365 environments with deep OS integration.', 'MSPs with heavy Microsoft 365 client base', 'per_seat', 8, 14, 'seat', 'all', ARRAY['HIPAA','PCI DSS','CMMC'], ARRAY['endpoint','edr','microsoft','m365']),
('Huntress', 'Huntress', 'edr', 'SMB EDR', 'Managed EDR and threat hunting built specifically for MSPs serving SMBs.', 'MSPs serving SMB clients who need managed threat hunting', 'per_seat', 5, 10, 'seat', 'smb', ARRAY['HIPAA','CMMC'], ARRAY['endpoint','edr','managed','smb']),
('Malwarebytes for Teams', 'Malwarebytes', 'edr', 'SMB Endpoint', 'Lightweight endpoint protection and remediation for small business environments.', 'MSPs needing affordable endpoint protection for cost-sensitive SMB clients', 'per_seat', 4, 8, 'seat', 'smb', ARRAY[]::text[], ARRAY['endpoint','lightweight','smb']),
('Webroot Business Endpoint', 'OpenText', 'edr', 'Cloud Endpoint', 'Cloud-based endpoint protection with fast scans and low resource usage.', 'MSPs needing lightweight endpoint protection for older hardware environments', 'per_seat', 3, 6, 'seat', 'smb', ARRAY[]::text[], ARRAY['endpoint','cloud','lightweight']),
('Trend Micro Vision One', 'Trend Micro', 'edr', 'XDR Platform', 'Extended detection and response across endpoints, email, and cloud.', 'MSPs wanting unified XDR visibility across multiple attack surfaces', 'per_seat', 14, 20, 'seat', 'all', ARRAY['HIPAA','PCI DSS','CMMC'], ARRAY['edr','xdr','endpoint']),
('ESET Protect', 'ESET', 'edr', 'Multi-Layer Endpoint', 'Multi-layered endpoint security with strong European compliance credentials.', 'MSPs with European clients or GDPR compliance requirements', 'per_seat', 6, 12, 'seat', 'all', ARRAY['HIPAA'], ARRAY['endpoint','gdpr','multi-layer']),

-- ── MANAGED DETECTION & RESPONSE (MDR) ──────────────────────────────────────
('Arctic Wolf MDR', 'Arctic Wolf', 'mdr', 'Co-Managed SOC', '24/7 co-managed SOC with dedicated Concierge Security Team per client.', 'MSPs wanting to offer a white-glove SOC experience', 'flat', 1500, 4000, 'month', 'mid_market', ARRAY['HIPAA','PCI DSS','CMMC','SOC2'], ARRAY['mdr','soc','co-managed']),
('Secureworks Taegis MDR', 'Secureworks', 'mdr', 'Enterprise MDR', 'Enterprise-grade MDR with proprietary Taegis XDR platform.', 'MSSPs serving mid-market to enterprise clients', 'flat', 3000, 8000, 'month', 'enterprise', ARRAY['HIPAA','PCI DSS','CMMC','NIST'], ARRAY['mdr','enterprise','xdr']),
('Red Canary MDR', 'Red Canary', 'mdr', 'Threat Detection', '24/7 threat detection and response with high-fidelity alerts and rapid investigation.', 'MSPs wanting to eliminate alert fatigue with high-signal detection', 'per_seat', 12, 18, 'seat', 'mid_market', ARRAY['HIPAA','PCI DSS'], ARRAY['mdr','threat-hunting','low-noise']),
('Blackpoint Cyber MDR', 'Blackpoint Cyber', 'mdr', 'MSP-Native MDR', 'MDR built specifically for MSPs with 24/7 SOC and lateral movement detection.', 'MSPs wanting an MDR purpose-built for their delivery model', 'per_seat', 8, 15, 'seat', 'smb', ARRAY['HIPAA','CMMC'], ARRAY['mdr','msp-native','lateral-movement']),
('Coro MDR', 'Coro', 'mdr', 'SMB MDR', 'All-in-one cybersecurity platform with MDR tailored for SMB MSPs.', 'MSPs looking for a consolidated MDR + endpoint + email platform for SMBs', 'per_seat', 6, 12, 'seat', 'smb', ARRAY['HIPAA'], ARRAY['mdr','smb','consolidated']),
('Expel MDR', 'Expel', 'mdr', 'Transparent MDR', 'MDR with full transparency — clients see every alert and analyst action.', 'MSPs with sophisticated clients who want visibility into SOC operations', 'flat', 2000, 5000, 'month', 'mid_market', ARRAY['HIPAA','PCI DSS','SOC2'], ARRAY['mdr','transparent','sophisticated']),

-- ── SIEM & LOG MANAGEMENT ───────────────────────────────────────────────────
('Microsoft Sentinel', 'Microsoft', 'siem', 'Cloud SIEM', 'Cloud-native SIEM with AI-driven analytics built on Azure.', 'MSPs with Microsoft-heavy environments wanting cloud-native SIEM', 'usage', 100, 500, 'month', 'mid_market', ARRAY['HIPAA','PCI DSS','CMMC','NIST'], ARRAY['siem','azure','cloud','microsoft']),
('Splunk Enterprise Security', 'Splunk', 'siem', 'Enterprise SIEM', 'Industry-leading SIEM for complex enterprise environments with deep analytics.', 'MSSPs serving large enterprise clients with complex compliance requirements', 'usage', 2000, 10000, 'month', 'enterprise', ARRAY['HIPAA','PCI DSS','CMMC','SOC2','NIST'], ARRAY['siem','enterprise','analytics']),
('IBM QRadar', 'IBM', 'siem', 'Enterprise SIEM', 'Full-featured SIEM with advanced correlation and compliance reporting.', 'MSSPs needing enterprise SIEM with deep IBM ecosystem integration', 'flat', 1500, 5000, 'month', 'enterprise', ARRAY['HIPAA','PCI DSS','CMMC','SOC2'], ARRAY['siem','enterprise','ibm']),
('Elastic Security', 'Elastic', 'siem', 'Open SIEM', 'Open-source SIEM platform with flexible deployment and powerful search.', 'Tech-forward MSPs wanting customizable, open SIEM infrastructure', 'flat', 500, 2000, 'month', 'mid_market', ARRAY['HIPAA','PCI DSS','NIST'], ARRAY['siem','open-source','elastic','flexible']),
('LogRhythm SIEM', 'LogRhythm', 'siem', 'Full-Stack SIEM', 'Full-stack SIEM with built-in UEBA, SOAR, and NDR capabilities.', 'MSSPs wanting a comprehensive SIEM with automated response', 'flat', 2000, 6000, 'month', 'enterprise', ARRAY['HIPAA','PCI DSS','CMMC','NIST'], ARRAY['siem','ueba','soar','full-stack']),
('Devo SIEM', 'Devo', 'siem', 'Cloud SIEM', 'Cloud-native SIEM with real-time analytics and multi-tenant architecture built for MSSPs.', 'MSSPs needing true multi-tenant SIEM for client isolation', 'usage', 800, 3000, 'month', 'mid_market', ARRAY['HIPAA','PCI DSS','SOC2'], ARRAY['siem','multi-tenant','mssp-native']),

-- ── IDENTITY & ACCESS MANAGEMENT ────────────────────────────────────────────
('Microsoft Entra ID', 'Microsoft', 'idp', 'Cloud Identity', 'Cloud identity and access management with SSO, MFA, and conditional access.', 'MSPs with Microsoft 365 clients needing cloud identity management', 'per_seat', 6, 12, 'seat', 'all', ARRAY['HIPAA','PCI DSS','CMMC'], ARRAY['identity','mfa','sso','microsoft','azure-ad']),
('Okta Workforce Identity', 'Okta', 'idp', 'Enterprise IAM', 'Enterprise identity platform with SSO, MFA, lifecycle management, and zero trust.', 'MSPs with multi-vendor environments needing vendor-neutral identity', 'per_seat', 8, 16, 'seat', 'mid_market', ARRAY['HIPAA','PCI DSS','SOC2','NIST'], ARRAY['identity','mfa','sso','zero-trust']),
('CyberArk PAM', 'CyberArk', 'idp', 'Privileged Access', 'Privileged access management for securing admin credentials and service accounts.', 'MSPs managing high-security environments with strict privileged access requirements', 'per_seat', 15, 30, 'seat', 'enterprise', ARRAY['HIPAA','PCI DSS','CMMC','SOC2'], ARRAY['pam','privileged-access','admin']),
('BeyondTrust Remote Support', 'BeyondTrust', 'idp', 'Privileged Remote', 'Privileged remote access and session management for MSP technicians and clients.', 'MSPs needing secure, audited remote access to client environments', 'flat', 800, 2500, 'month', 'all', ARRAY['HIPAA','PCI DSS','CMMC'], ARRAY['pam','remote-access','session-recording']),
('Duo Security', 'Cisco', 'idp', 'MFA Platform', 'Multi-factor authentication and zero-trust access for any application.', 'MSPs needing simple, reliable MFA deployment across diverse client apps', 'per_seat', 3, 9, 'seat', 'all', ARRAY['HIPAA','PCI DSS','CMMC'], ARRAY['mfa','2fa','zero-trust','cisco']),
('JumpCloud Directory', 'JumpCloud', 'idp', 'Cloud Directory', 'Cloud directory platform replacing Active Directory with cross-OS device and identity management.', 'MSPs with cross-platform (Mac/Windows/Linux) client environments', 'per_seat', 8, 15, 'seat', 'smb', ARRAY['HIPAA','PCI DSS'], ARRAY['directory','active-directory','cross-platform','mac']),

-- ── BACKUP & DISASTER RECOVERY ──────────────────────────────────────────────
('Datto BCDR', 'Datto', 'backup', 'MSP BCDR', 'Business continuity and disaster recovery with instant virtualization and cloud backup.', 'MSPs needing gold-standard BCDR with instant recovery and offsite redundancy', 'per_device', 50, 150, 'device', 'all', ARRAY['HIPAA','PCI DSS','CMMC'], ARRAY['backup','bcdr','disaster-recovery','instant-recovery']),
('Veeam Backup & Replication', 'Veeam', 'backup', 'Enterprise Backup', 'Enterprise backup and replication for virtual, physical, and cloud workloads.', 'MSPs with complex VM environments needing enterprise-grade backup', 'per_seat', 10, 25, 'seat', 'mid_market', ARRAY['HIPAA','PCI DSS','CMMC'], ARRAY['backup','vm','enterprise','replication']),
('Acronis Cyber Protect', 'Acronis', 'backup', 'Integrated Backup', 'Backup with integrated cybersecurity — combines backup, anti-ransomware, and endpoint protection.', 'MSPs wanting to consolidate backup and basic security into one agent', 'per_seat', 8, 18, 'seat', 'all', ARRAY['HIPAA','PCI DSS'], ARRAY['backup','integrated','anti-ransomware','msp']),
('Backblaze for Business', 'Backblaze', 'backup', 'Cloud Backup', 'Simple, affordable cloud backup for endpoints and servers.', 'MSPs needing low-cost cloud backup for cost-sensitive SMB clients', 'per_seat', 3, 8, 'seat', 'smb', ARRAY[]::text[], ARRAY['backup','cloud','affordable','simple']),
('Axcient x360Recover', 'Axcient', 'backup', 'MSP BCDR', 'MSP-exclusive BCDR platform with chain-free backup and AirGap ransomware protection.', 'MSPs wanting purpose-built BCDR with ransomware-proof immutable backups', 'per_device', 40, 120, 'device', 'all', ARRAY['HIPAA','CMMC'], ARRAY['backup','bcdr','immutable','msp-native']),
('Cove Data Protection', 'N-able', 'backup', 'MSP Backup', 'Cloud-first backup for endpoints, servers, and Microsoft 365 built for MSP delivery.', 'MSPs in the N-able ecosystem needing integrated backup management', 'per_seat', 5, 12, 'seat', 'smb', ARRAY['HIPAA'], ARRAY['backup','cloud','microsoft-365','n-able']),

-- ── NETWORK SECURITY ────────────────────────────────────────────────────────
('Cisco Meraki', 'Cisco', 'network', 'Cloud Networking', 'Cloud-managed networking with built-in security, SD-WAN, and centralized management.', 'MSPs managing multi-site clients who need centralized network visibility', 'flat', 200, 800, 'month', 'mid_market', ARRAY['PCI DSS','HIPAA'], ARRAY['network','sd-wan','firewall','cisco','cloud-managed']),
('Fortinet FortiGate', 'Fortinet', 'network', 'NGFW', 'Next-generation firewall with SD-WAN, IPS, and deep packet inspection.', 'MSPs needing enterprise-grade firewall with integrated SD-WAN', 'flat', 300, 1200, 'month', 'all', ARRAY['PCI DSS','HIPAA','CMMC'], ARRAY['firewall','ngfw','sd-wan','fortinet']),
('Palo Alto Networks NGFW', 'Palo Alto', 'network', 'Enterprise NGFW', 'Industry-leading next-gen firewall with App-ID and advanced threat prevention.', 'MSSPs serving enterprise clients with complex network segmentation requirements', 'flat', 800, 3000, 'month', 'enterprise', ARRAY['PCI DSS','HIPAA','CMMC','NIST'], ARRAY['firewall','ngfw','enterprise','zero-trust']),
('Sophos XGS Firewall', 'Sophos', 'network', 'MSP Firewall', 'Synchronized security firewall with direct integration to Sophos endpoint.', 'MSPs in the Sophos ecosystem wanting synchronized network and endpoint security', 'flat', 200, 600, 'month', 'smb', ARRAY['PCI DSS','HIPAA'], ARRAY['firewall','synchronized','sophos','msp']),
('WatchGuard Firebox', 'WatchGuard', 'network', 'SMB Firewall', 'Unified threat management with total security suite for SMB environments.', 'MSPs needing all-in-one UTM appliance for SMB clients', 'flat', 150, 500, 'month', 'smb', ARRAY['PCI DSS','HIPAA'], ARRAY['firewall','utm','smb','watchguard']),

-- ── EMAIL SECURITY ──────────────────────────────────────────────────────────
('Microsoft Defender for Office 365', 'Microsoft', 'email-security', 'Email Protection', 'Advanced email threat protection integrated with Microsoft 365.', 'MSPs managing Microsoft 365 environments needing integrated email security', 'per_seat', 3, 8, 'seat', 'all', ARRAY['HIPAA','PCI DSS'], ARRAY['email','phishing','microsoft','m365']),
('Proofpoint Essentials', 'Proofpoint', 'email-security', 'SMB Email Security', 'Advanced email security with anti-phishing, spam filtering, and email archiving for SMBs.', 'MSPs needing enterprise-class email protection at SMB price points', 'per_seat', 4, 9, 'seat', 'smb', ARRAY['HIPAA','PCI DSS'], ARRAY['email','phishing','archiving','smb']),
('Mimecast Email Security', 'Mimecast', 'email-security', 'Cloud Email Security', 'Cloud-based email security with advanced threat protection and email resilience.', 'MSPs needing comprehensive email security with continuity and archiving', 'per_seat', 5, 12, 'seat', 'all', ARRAY['HIPAA','PCI DSS','CMMC'], ARRAY['email','cloud','continuity','archiving']),
('Abnormal Security', 'Abnormal', 'email-security', 'AI Email Security', 'AI-native email security that detects sophisticated BEC and account takeover attacks.', 'MSPs serving clients targeted by sophisticated phishing and BEC attacks', 'per_seat', 4, 10, 'seat', 'mid_market', ARRAY['HIPAA','PCI DSS'], ARRAY['email','ai','bec','account-takeover']),
('Barracuda Email Protection', 'Barracuda', 'email-security', 'Email + Archiving', 'Email security with phishing simulation, archiving, and backup in one platform.', 'MSPs wanting email security bundled with training and archiving', 'per_seat', 4, 10, 'seat', 'smb', ARRAY['HIPAA','PCI DSS'], ARRAY['email','training','archiving','backup']),

-- ── VULNERABILITY MANAGEMENT ────────────────────────────────────────────────
('Tenable.io', 'Tenable', 'vulnerability', 'Enterprise VM', 'Cloud-based vulnerability management with asset discovery and risk-based prioritization.', 'MSSPs managing vulnerability programs for mid-market to enterprise clients', 'per_seat', 8, 20, 'seat', 'mid_market', ARRAY['PCI DSS','HIPAA','CMMC','NIST'], ARRAY['vulnerability','scanning','risk','compliance']),
('Qualys VMDR', 'Qualys', 'vulnerability', 'Cloud VM', 'Cloud-native vulnerability, patch, and compliance management in one platform.', 'MSPs needing VM + patch management consolidated on one platform', 'per_seat', 6, 15, 'seat', 'all', ARRAY['PCI DSS','HIPAA','CMMC'], ARRAY['vulnerability','patch','compliance','cloud']),
('Rapid7 InsightVM', 'Rapid7', 'vulnerability', 'Live VM', 'Live vulnerability management with real-time risk scoring and attacker analytics.', 'MSPs wanting live VM visibility with integrated threat intelligence', 'per_seat', 8, 18, 'seat', 'mid_market', ARRAY['PCI DSS','HIPAA','NIST'], ARRAY['vulnerability','risk','live','analytics']),
('Action1 Patch Management', 'Action1', 'vulnerability', 'SMB Patch', 'Cloud-native patch management built for MSPs, with free tier for small environments.', 'MSPs needing affordable, easy patch management for SMB clients', 'per_endpoint', 0, 3, 'endpoint', 'smb', ARRAY['CMMC'], ARRAY['patch','vulnerability','smb','affordable']),

-- ── DNS FILTERING & WEB SECURITY ────────────────────────────────────────────
('Cisco Umbrella', 'Cisco', 'dns-filtering', 'DNS Security', 'Cloud-delivered DNS security with threat intelligence from Cisco Talos.', 'MSPs wanting Cisco-backed DNS protection with broad threat intelligence', 'per_seat', 3, 7, 'seat', 'all', ARRAY['HIPAA','PCI DSS','CMMC'], ARRAY['dns','web-filtering','cisco','cloud']),
('DNSFilter', 'DNSFilter', 'dns-filtering', 'MSP DNS', 'AI-powered DNS filtering built for MSPs with multi-tenant management.', 'MSPs wanting MSP-native DNS filtering with simple per-site management', 'per_seat', 1, 4, 'seat', 'all', ARRAY['HIPAA'], ARRAY['dns','filtering','ai','msp-native']),
('Webroot DNS Protection', 'OpenText', 'dns-filtering', 'DNS Shield', 'DNS-layer protection to block threats before they reach endpoints.', 'MSPs in the Webroot ecosystem wanting add-on DNS protection', 'per_seat', 1, 3, 'seat', 'smb', ARRAY[]::text[], ARRAY['dns','filtering','webroot']),
('Akamai ETP', 'Akamai', 'dns-filtering', 'Enterprise DNS', 'Enterprise DNS security with zero trust network access capabilities.', 'MSSPs serving enterprise clients needing carrier-grade DNS security', 'per_seat', 5, 12, 'seat', 'enterprise', ARRAY['HIPAA','PCI DSS','NIST'], ARRAY['dns','enterprise','zero-trust','akamai']),

-- ── PATCH MANAGEMENT ────────────────────────────────────────────────────────
('NinjaRMM Patching', 'NinjaOne', 'patch', 'RMM Patching', 'Automated patch management integrated with NinjaOne RMM for Windows, Mac, and third-party apps.', 'MSPs using NinjaOne RMM wanting integrated patch management', 'per_device', 3, 6, 'device', 'all', ARRAY['CMMC','HIPAA'], ARRAY['patch','rmm','ninja','automated']),
('ManageEngine Patch Manager', 'ManageEngine', 'patch', 'Enterprise Patching', 'Comprehensive patch management for Windows, Mac, Linux, and 900+ third-party apps.', 'MSPs needing broad OS and application patching coverage', 'per_endpoint', 2, 5, 'endpoint', 'all', ARRAY['CMMC','PCI DSS'], ARRAY['patch','cross-platform','enterprise']),
('Automox', 'Automox', 'patch', 'Cloud Patching', 'Cloud-native patch management for any OS from a single console.', 'MSPs managing hybrid Windows/Mac/Linux environments wanting cloud-native patching', 'per_device', 3, 7, 'device', 'all', ARRAY['CMMC','PCI DSS'], ARRAY['patch','cloud','cross-platform','automated']),

-- ── DARK WEB MONITORING ─────────────────────────────────────────────────────
('Flare Threat Exposure', 'Flare', 'dark-web', 'Threat Exposure', 'Continuous dark web and clear web monitoring for leaked credentials, ransomware mentions, and brand exposure.', 'MSSPs wanting comprehensive dark web and threat exposure monitoring for clients', 'per_seat', 3, 8, 'seat', 'all', ARRAY['HIPAA','PCI DSS'], ARRAY['dark-web','credentials','threat-intel','monitoring']),
('SpyCloud ATO Prevention', 'SpyCloud', 'dark-web', 'ATO Prevention', 'Account takeover prevention using recaptured breach data to detect exposed credentials.', 'MSPs focused on preventing credential-based breaches and account takeovers', 'per_seat', 4, 10, 'seat', 'mid_market', ARRAY['HIPAA','PCI DSS'], ARRAY['dark-web','ato','credentials','breach']),
('ID Agent Dark Web ID', 'Kaseya', 'dark-web', 'SMB Dark Web', 'Dark web monitoring for SMBs with credential compromise alerts built for MSPs.', 'MSPs in the Kaseya ecosystem needing dark web monitoring for SMB clients', 'per_seat', 2, 5, 'seat', 'smb', ARRAY[]::text[], ARRAY['dark-web','smb','credentials','kaseya']),

-- ── COMPLIANCE & GRC ────────────────────────────────────────────────────────
('Drata', 'Drata', 'compliance', 'Compliance Automation', 'Automated compliance monitoring for SOC 2, ISO 27001, HIPAA, and more.', 'MSPs offering compliance advisory services to clients pursuing certifications', 'flat', 500, 2000, 'month', 'mid_market', ARRAY['HIPAA','SOC2'], ARRAY['compliance','automation','soc2','iso27001']),
('Vanta', 'Vanta', 'compliance', 'Trust Management', 'Security compliance automation with continuous monitoring and audit evidence collection.', 'MSPs helping tech-company clients achieve and maintain compliance certifications', 'flat', 500, 1500, 'month', 'mid_market', ARRAY['HIPAA','SOC2','PCI DSS'], ARRAY['compliance','automation','trust','evidence']),
('Cynomi vCISO Platform', 'Cynomi', 'compliance', 'vCISO Platform', 'AI-powered vCISO platform for MSPs to deliver security assessments and compliance roadmaps.', 'MSPs wanting to offer vCISO and compliance advisory services at scale', 'flat', 200, 800, 'month', 'all', ARRAY['HIPAA','PCI DSS','CMMC','NIST'], ARRAY['vciso','compliance','assessment','advisory']),
('Compliancy Group', 'Compliancy Group', 'compliance', 'HIPAA Compliance', 'HIPAA compliance software and coaching for healthcare industry clients.', 'MSPs serving healthcare clients needing structured HIPAA compliance support', 'flat', 300, 800, 'month', 'smb', ARRAY['HIPAA'], ARRAY['hipaa','healthcare','compliance','coaching']),

-- ── PSA & RMM (Operational Tools) ───────────────────────────────────────────
('ConnectWise Manage', 'ConnectWise', 'psa', 'MSP PSA', 'Professional services automation for ticketing, billing, and project management.', 'MSPs using ConnectWise ecosystem for operations management', 'per_seat', 50, 120, 'seat', 'all', ARRAY[]::text[], ARRAY['psa','ticketing','billing','connectwise']),
('Autotask PSA', 'Datto', 'psa', 'Cloud PSA', 'Cloud PSA with ticketing, time tracking, billing, and project management.', 'MSPs in the Datto ecosystem needing integrated PSA', 'per_seat', 40, 100, 'seat', 'all', ARRAY[]::text[], ARRAY['psa','cloud','datto','ticketing']),
('HaloPSA', 'Halo', 'psa', 'Modern PSA', 'Modern PSA with ITIL-aligned service management and deep automation capabilities.', 'MSPs wanting a modern, highly customizable PSA with strong automation', 'per_seat', 30, 70, 'seat', 'all', ARRAY[]::text[], ARRAY['psa','itil','automation','modern']),
('NinjaOne RMM', 'NinjaOne', 'rmm', 'Cloud RMM', 'Cloud-first RMM with remote access, patch management, and monitoring in one platform.', 'MSPs wanting an all-in-one RMM with modern UX and fast deployment', 'per_device', 3, 6, 'device', 'all', ARRAY[]::text[], ARRAY['rmm','monitoring','remote-access','patch']),
('ConnectWise Automate', 'ConnectWise', 'rmm', 'Scripting RMM', 'RMM with powerful scripting and automation capabilities for complex environments.', 'MSPs needing deep automation and scripting for complex client environments', 'per_device', 4, 8, 'device', 'all', ARRAY[]::text[], ARRAY['rmm','automation','scripting','connectwise']),
('Atera RMM', 'Atera', 'rmm', 'All-in-One MSP', 'All-in-one RMM + PSA with fixed per-technician pricing (unlimited endpoints).', 'Small MSPs wanting unlimited endpoint management without per-device costs', 'per_seat', 99, 149, 'seat', 'smb', ARRAY[]::text[], ARRAY['rmm','psa','all-in-one','unlimited']);
